---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperZnode
metadata:
  name: simple-hdfs-znode
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  clusterRef:
    name: simple-zk
